title: "Stefano Ninfole"
description: |-
  I am Stefano, a PhD researcher in Economics. My research focuses on the markets and policy of decarbonization technologies. My academic interests, which run through all my papers, span from microeconomic theoretical modelling to structural time-series econometrics. Many would argue you couldn't find two interests further apart on the spectrum. I agree. But I can't help it.

  I have a background in Economics, Finance and Insurance from Università del Salento. I am based in Oslo and particularly affectionate to Berlin, where I spent a six-month research stay at DIW. If any of my research topics resonate with you, or you're simply curious and would like to discuss them, please send me an email. I'd love to hear from you!
name: "Stefano Ninfole"
email: "stefano.ninfole@nmbu.no"
tagline: "PhD researcher in Economics"

url: "https://sninfole.github.io"
lang: en
author:
  name: "Stefano Ninfole"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
exclude:
  - "BUONAI_web copia.jpg"
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
